title: FAIR Vocabularies
description: A website for the guidelines for FAIR vocabularies.
theme: jekyll-theme-leap-day

header_pages:
  - _pages/main.md
  - _pages/makeVocabularyFAIR.md

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - _pages
  
exclude: 
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
